### PR TITLE
Enable es5: initial draft

### PR DESCRIPTION
**Pull request by olsonpm**
- change main entry to ./index.js
 - add logic to dynamically export the appropriate lib version and polyfill
   'Promise' if necessary
 - add prepublish script
 - add node-version and promise-polyfill dependencies
 - add necessary babel dev dependencies
 - remove engine declaration in package.json
 - add babel configuration

### CODE REVIEW

**Comment by olsonpm** [comment]
I do want your opinion on whether testing the es5 version is necessary.  I tested back to node 0.10 and it worked.  There are a couple issues with automating a test script (as far as I can tell anyway)

- We have to assume the developer has nvm
- It would be easier to export ChildProcessPromise on the root export so test.js doesn't hardcode the lib directory

If you're fine with me assuming nvm and exporting ChildProcessPromise on the root export, then I'll add an script to test the es5 output.

**Comment by patrick-steele-idem** [comment]
Reviewing PR now.

> I do want your input on how to test the es5 output.

We can enable Travis CI since it allows you to run tests against multiple Node.js versions by specifying the versions in a `.travis.yml` file. For example: [marko/.travis.yml](https://github.com/marko-js/marko/blob/d4695e1a66dd5e7aebc70ac3800dd7937bec21a0/.travis.yml#L2-L5)

**Comment by patrick-steele-idem** [comment]
I made various fixes on top of your changes and enabled Travis CI. Everything appears to be working in all Node.js versions. New version published: `child-process-promise@2.1.0`

Please let me know if you see any issues. Thanks for your help on this!

**Comment by olsonpm** [comment]
Sounds great - haven't worked with Travis CI  before so that will be good for me to learn.  I'll take a look tonight and delete my branch assuming all's well.

**Comment by olsonpm** [comment]
Aye - my bad about depending on babel instead of babel-cli

Also I appreciate your comment `Don't use the native Promise in Node.js <4 since it doesn't support subclassing` - never knew that

Thanks so much for implementing this in a short time.

**Comment by patrick-steele-idem** [comment]
You're welcome and thank you.

> Also I appreciate your comment "Don't use the native Promise in Node.js <4 since it doesn't support subclassing" - never knew that

I learned this during the implementation. I don't remember the exact error, but things blew up when trying to use the native `Promise` implementation provided with Node.js `v0.12`. Using the polyfill is okay because the `Promise` spec makes it clear that different `Promise` implementations should play nice together.

**Pull request merged**
